### ISSUE TITLE
[week 1] Rotten Tomatoes

### ISSUE THREAD

**Issue by mLewisLogic** [mLewisLogic/codepath-assignment1#1]
Week 1 assignment.

Unfortunately, no time for optionals, but the basics are working well.

/cc @codepath

**Comment by stepan** [comment]
Hey Mike,

For future assignments please format the the required and optional stories property so it's easier to see what stories are done. You can see an example template [here](https://gist.githubusercontent.com/timothy1ee/b9b1860c8ecb4b0b1c18/raw/2adc3f63677d81644e00245cee891eee88907767/gistfile1.md)

**Comment by codepathreview** [comment]
:+1: nice work. The point of this homework was to explore a simple example of a full MVC application with a RESTful API. For each point in the homework feedback checklist, I'll either confirm that you're on the right track with the implementation, or I'll provide some feedback:
- Nice code styling. Check out these Swift style guides: 
  - [Ray Wenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide) 
  - [Github Swift Style Guide](https://github.com/github/swift-style-guide)
- Nice work with the access controls in the classes. You should always try to minimize the number of properties and functions that are public or internal.
- In future homework, we will cover how to implement models that can deserialize from an NSDictionary. SwiftyJSON is a useful project for making it easier to deserialize the JSON response.
- Your custom Movie cell should have a property called `movie`. In the custom setter of `movie`, you should configure the various labels and images. This decouples your custom cells from the table view controllers.
- Nice work loading the images asynchronously.
- Note that your images are stretched. You should observe the UIContentMode of the UIImageView. By default, it will stretch the image to match your dimensions, which is probably not what you want.
- Nice work implementing the error message on network failure.

In general, you should challenge yourself to create visually polished applications. That's where you'll find all the rough edges of the iOS framework and earn the next level of mastery.

**Comment by mLewisLogic** [comment]
:+1: Thanks for the thorough review! Will incorporate into this week's assignment.
